config/routes.rb
Rails.application.routes.draw do
  resources :pedidos
  resources :faleconoscos
  resources :produtos
  resources :clientes
  root to: 'visitors#index'

end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente was successfully created.' }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'Cliente was successfully updated.' }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: 'Cliente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:nome, :endereco, :telefone, :email)
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_form.html.haml
= simple_form_for(@cliente) do |f|
  = f.error_notification

  .form-inputs
    = f.input :nome, label: "Nome", label_method: :nome
    = f.input :endereco, label: "Endereço"
    = f.input :telefone, label: "Telefone"
    = f.input :email, label: "E-mail"

  .form-actions
    = f.submit "Salvar"

app/views/clientes/edit.html.haml
%h1 Editing cliente

= render 'form'

= link_to 'Mostrar', @cliente
\|
= link_to 'Voltar', clientes_path

app/views/clientes/index.html.haml
%h1 CLIENTES

%table
  %thead
    %tr
      %th Nome
      %th Endereco
      %th Telefone
      %th Email
      %th
      %th
      %th

  %tbody
    - @clientes.each do |cliente|
      %tr
        %td= cliente.nome
        %td= cliente.endereco
        %td= cliente.telefone
        %td= cliente.email
        %td= link_to 'Mostrar', cliente
        %td= link_to 'Editar', edit_cliente_path(cliente)
        %td= link_to 'Destroy', cliente, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'Novo Cliente', new_cliente_path

app/views/clientes/new.html.haml
%h1 New cliente

= render 'form'

= link_to 'Voltar', clientes_path

app/views/clientes/show.html.haml
%p#notice= notice

%p
  %b Nome:
  = @cliente.nome
%p
  %b Endereco:
  = @cliente.endereco
%p
  %b Telefone:
  = @cliente.telefone
%p
  %b Email:
  = @cliente.email

= link_to 'Editar', edit_cliente_path(@cliente)
\|
= link_to 'Voltar', clientes_path