config/routes.rb
Rails.application.routes.draw do
  resources :pedidos
  resources :faleconoscos
  resources :produtos
  resources :clientes
  root to: 'visitors#index'

end

app/models/faleconosco.rb
class Faleconosco < ActiveRecord::Base
  belongs_to :Cliente
end

app/controllers/faleconoscos_controller.rb
class FaleconoscosController < ApplicationController
  before_action :set_faleconosco, only: [:show, :edit, :update, :destroy]

  # GET /faleconoscos
  # GET /faleconoscos.json
  def index
    @faleconoscos = Faleconosco.all
  end

  # GET /faleconoscos/1
  # GET /faleconoscos/1.json
  def show
  end

  # GET /faleconoscos/new
  def new
    @faleconosco = Faleconosco.new
  end

  # GET /faleconoscos/1/edit
  def edit
  end

  # POST /faleconoscos
  # POST /faleconoscos.json
  def create
    @faleconosco = Faleconosco.new(faleconosco_params)

    respond_to do |format|
      if @faleconosco.save
        format.html { redirect_to @faleconosco, notice: 'Faleconosco was successfully created.' }
        format.json { render :show, status: :created, location: @faleconosco }
      else
        format.html { render :new }
        format.json { render json: @faleconosco.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /faleconoscos/1
  # PATCH/PUT /faleconoscos/1.json
  def update
    respond_to do |format|
      if @faleconosco.update(faleconosco_params)
        format.html { redirect_to @faleconosco, notice: 'Faleconosco was successfully updated.' }
        format.json { render :show, status: :ok, location: @faleconosco }
      else
        format.html { render :edit }
        format.json { render json: @faleconosco.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /faleconoscos/1
  # DELETE /faleconoscos/1.json
  def destroy
    @faleconosco.destroy
    respond_to do |format|
      format.html { redirect_to faleconoscos_url, notice: 'Faleconosco was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_faleconosco
      @faleconosco = Faleconosco.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def faleconosco_params
      params.require(:faleconosco).permit(:Cliente_id, :email, :assunto, :conteudo)
    end
end

app/helpers/faleconoscos_helper.rb
module FaleconoscosHelper
end

app/views/faleconoscos/_form.html.haml
= simple_form_for(@faleconosco) do |f|
  = f.error_notification

  .form-inputs
    = f.association :Cliente, label: "Nome", label_method: :nome
    = f.input :email, label: "Email"
    = f.input :assunto, label: "Assunto"
    = f.input :conteudo, label: "Conteudo"

  .form-actions
    = f.submit "Salvar"

app/views/faleconoscos/edit.html.haml
%h1 Editing faleconosco

= render 'form'

= link_to 'Mostrar', @faleconosco
\|
= link_to 'Voltar', faleconoscos_path

app/views/faleconoscos/index.html.haml
%h1 FALECONOSCO

%table
  %thead
    %tr
      %th Cliente
      %th Email
      %th Assunto
      %th Conteudo
      %th
      %th
      %th

  %tbody
    - @faleconoscos.each do |faleconosco|
      %tr
        %td= faleconosco.Cliente.nome
        %td= faleconosco.email
        %td= faleconosco.assunto
        %td= faleconosco.conteudo
        %td= link_to 'Mostrar', faleconosco
        %td= link_to 'Editar', edit_faleconosco_path(faleconosco)
        %td= link_to 'Destroy', faleconosco, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'Novo FaleConosco', new_faleconosco_path

app/views/faleconoscos/new.html.haml
%h1 New faleconosco

= render 'form'

= link_to 'Voltar', faleconoscos_path

app/views/faleconoscos/show.html.haml
%p#notice= notice

%p
  %b Cliente:
  = @faleconosco.Cliente.nome
%p
  %b Email:
  = @faleconosco.email
%p
  %b Assunto:
  = @faleconosco.assunto
%p
  %b Conteudo:
  = @faleconosco.conteudo

= link_to 'Editar', edit_faleconosco_path(@faleconosco)
\|
= link_to 'Voltar', faleconoscos_path