config/routes.rb
Rails.application.routes.draw do
  resources :pedidos
  resources :faleconoscos
  resources :produtos
  resources :clientes
  root to: 'visitors#index'

end

app/models/pedido.rb
class Pedido < ActiveRecord::Base
  belongs_to :Cliente
  belongs_to :Produto
end

app/controllers/pedidos_controller.rb
class PedidosController < ApplicationController
  before_action :set_pedido, only: [:show, :edit, :update, :destroy]

  # GET /pedidos
  # GET /pedidos.json
  def index
    @pedidos = Pedido.all
  end

  # GET /pedidos/1
  # GET /pedidos/1.json
  def show
  end

  # GET /pedidos/new
  def new
    @pedido = Pedido.new
  end

  # GET /pedidos/1/edit
  def edit
  end

  # POST /pedidos
  # POST /pedidos.json
  def create
    @pedido = Pedido.new(pedido_params)

    respond_to do |format|
      if @pedido.save
        format.html { redirect_to @pedido, notice: 'Pedido was successfully created.' }
        format.json { render :show, status: :created, location: @pedido }
      else
        format.html { render :new }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pedidos/1
  # PATCH/PUT /pedidos/1.json
  def update
    respond_to do |format|
      if @pedido.update(pedido_params)
        format.html { redirect_to @pedido, notice: 'Pedido was successfully updated.' }
        format.json { render :show, status: :ok, location: @pedido }
      else
        format.html { render :edit }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pedidos/1
  # DELETE /pedidos/1.json
  def destroy
    @pedido.destroy
    respond_to do |format|
      format.html { redirect_to pedidos_url, notice: 'Pedido was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pedido
      @pedido = Pedido.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pedido_params
      params.require(:pedido).permit(:Cliente_id, :Produto_id, :quantidade, :valorunitario, :valor, :total)
    end
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/views/pedidos/_form.html.haml
= simple_form_for(@pedido) do |f|
  = f.error_notification

  .form-inputs
    = f.association :Cliente, label: "Nome Cliente", label_method: :nome
    = f.association :Produto, label: "Nome", label_method: :nome
    = f.input :quantidade
    = f.input :valorunitario, label: "Valorunitario"
    = f.input :valor
    = f.input :total

  .form-actions
    = f.submit "Salvar"

app/views/pedidos/edit.html.haml
%h1 Editing pedido

= render 'form'

= link_to 'Mostrar', @pedido
\|
= link_to 'Voltar', pedidos_path

app/views/pedidos/index.html.haml
%h1 PEDIDOS

%table
  %thead
    %tr
      %th Cliente
      %th Produto
      %th Quantidade
      %th Valorunitario
      %th Valor
      %th Total
      %th
      %th
      %th

  %tbody
    - @pedidos.each do |pedido|
      %tr
        %td= pedido.Cliente.nome
        %td= pedido.Produto.nome
        %td= pedido.quantidade
        %td= pedido.valorunitario
        %td= pedido.valor
        %td= pedido.total
        %td= link_to 'Mostrar', pedido
        %td= link_to 'Editar', edit_pedido_path(pedido)
        %td= link_to 'Destroy', pedido, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'Novo Pedido', new_pedido_path

app/views/pedidos/new.html.haml
%h1 New pedido

= render 'form'

= link_to 'Voltar', pedidos_path

app/views/pedidos/show.html.haml
%p#notice= notice

%p
  %b Cliente:
  = @pedido.Cliente.nome
%p
  %b Produto:
  = @pedido.Produto.nome
%p
  %b Quantidade:
  = @pedido.quantidade
%p
  %b Valorunitario:
  = @pedido.valorunitario
  %b Valor:
  = @pedido.valor
%p
  %b Total:
  = @pedido.total

= link_to 'Editar', edit_pedido_path(@pedido)
\|
= link_to 'Voltar', pedidos_path