config/routes.rb
Rails.application.routes.draw do
  resources :pedidos
  resources :faleconoscos
  resources :produtos
  resources :clientes
  root to: 'visitors#index'

end

app/models/produto.rb
class Produto < ActiveRecord::Base
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  before_action :set_produto, only: [:show, :edit, :update, :destroy]

  # GET /produtos
  # GET /produtos.json
  def index
    @produtos = Produto.all
  end

  # GET /produtos/1
  # GET /produtos/1.json
  def show
  end

  # GET /produtos/new
  def new
    @produto = Produto.new
  end

  # GET /produtos/1/edit
  def edit
  end

  # POST /produtos
  # POST /produtos.json
  def create
    @produto = Produto.new(produto_params)

    respond_to do |format|
      if @produto.save
        format.html { redirect_to @produto, notice: 'Produto was successfully created.' }
        format.json { render :show, status: :created, location: @produto }
      else
        format.html { render :new }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produtos/1
  # PATCH/PUT /produtos/1.json
  def update
    respond_to do |format|
      if @produto.update(produto_params)
        format.html { redirect_to @produto, notice: 'Produto was successfully updated.' }
        format.json { render :show, status: :ok, location: @produto }
      else
        format.html { render :edit }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1
  # DELETE /produtos/1.json
  def destroy
    @produto.destroy
    respond_to do |format|
      format.html { redirect_to produtos_url, notice: 'Produto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      @produto = Produto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def produto_params
      params.require(:produto).permit(:nome, :categoria, :descricao, :valor)
    end
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/produtos/_form.html.haml
= simple_form_for(@produto) do |f|
  = f.error_notification

  .form-inputs
    = f.input :nome, label: "Nome", label_method: :nome
    = f.input :categoria, label: "Categoria"
    = f.input :descricao, label: "Descricao"
    = f.input :valor, label: "Valor"

  .form-actions
    = f.submit "Salvar"

app/views/produtos/edit.html.haml
%h1 Editing produto

= render 'form'

= link_to 'Mostrar', @produto
\|
= link_to 'Voltar', produtos_path

app/views/produtos/index.html.haml
%h1 PRODUTOS

%table
  %thead
    %tr
      %th Nome
      %th Categoria
      %th Descricao
      %th Valor
      %th
      %th
      %th

  %tbody
    - @produtos.each do |produto|
      %tr
        %td= produto.nome
        %td= produto.categoria
        %td= produto.descricao
        %td= produto.valor
        %td= link_to 'Mostrar', produto
        %td= link_to 'Editar', edit_produto_path(produto)
        %td= link_to 'Destroy', produto, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'Novo Produto', new_produto_path

app/views/produtos/new.html.haml
%h1 New produto

= render 'form'

= link_to 'Voltar', produtos_path

app/views/produtos/show.html.haml
%p#notice= notice

%p
  %b Nome:
  = @produto.nome
%p
  %b Categoria:
  = @produto.categoria
%p
  %b Descricao:
  = @produto.descricao
%p
  %b Valor:
  = @produto.valor

= link_to 'Editar', edit_produto_path(@produto)
\|
= link_to 'Voltar', produtos_path